indent = 4
annotate_untyped_fields_with_any = false
join_lines_based_on_source = true
margin = 10_000
whitespace_in_kwargs = false
whitespace_typedefs = false
whitespace_ops_in_indices = false
import_to_using = false
pipe_to_function_call = false
long_to_short_function_def = false
align_struct_field = false
align_assignment = false
align_conditional = false
align_pair_arrow = false
conditional_to_if = false
normalize_line_endings = "auto"
align_matrix = false
indent_submodule = false
trailing_comma = true
trailing_zero = true
separate_kwargs_with_semicolon = true
surround_whereop_typeparameters = true
always_for_in = true
remove_extra_newlines = true
short_to_long_function_def = true
always_use_return = true
format_docstrings = false